---
- hosts: contao
  tasks:
  - name: 'Backup DB'
    include_role:
      name: backup
      tasks_from: db_backup
  - name: 'Contao Files'
    include_role:
      name: backup
      tasks_from: contao_files
