---
- hosts: all
  tasks:
  - name: 'Show Contao Version'
    command: "{{ php_path }} {{ websitePath }}/vendor/bin/contao-console contao:version"
    register: version
  - debug:
#     var: version.stdout_lines
      msg: "Contao Version - {{ version.stdout_lines }}"
