---
- hosts: contao
  tasks:
  - name: 'Write Configs'
    include_role:
      name: contao
      tasks_from: write_config

  - name: 'Install Contao Manager'
    include_role:
      name: contao
      tasks_from: install_manager

  - name: 'Install Contao'
    include_role:
      name: contao
      tasks_from: install_full
