---
- hosts: all
  tasks:
  - name: 'Show Contao Version'
    command: "{{ php_path }} {{ websitePath }}/vendor/bin/contao-console contao:version"
    register: version
  - debug:
     var: version.stdout_lines

  - name: 'Edit Composer JSON'
    replace:
      path: "{{ websitePath }}/composer.json"
      regexp: 'contao/(.*):.*\d\.\d+.*(".*)$'
      replace: 'contao/\1: "{{contao_version}}.*\2'
      backup: yes

  - name: 'Contao-Manager Update'
    shell: "{{ php_path }} -d memory_limit=-1 web/contao-manager.phar.php self-update"
    args:
      chdir: '{{ websitePath }}'
    register: update
  - debug:
     var: update.stdout_lines

  - name: 'Update Contao'
    shell: "{{ php_path }} -d memory_limit=-1 web/contao-manager.phar.php composer update --with-all-dependencies"
    args:
      chdir: '{{ websitePath }}'
    register: update
  - debug:
     var: update.stdout_lines

  - name: 'Write new CONFIG'
    include_role:
      name: contao
      tasks_from: write_config

  - name: 'Datenbankupdate for Contao'
    command: "{{ php_path }} -d memory_limit=-1 {{ websitePath }}/vendor/bin/contao-console contao:migrate"
    register: dbupdate
  - debug:
     var: dbupdate.stdout_lines

  - name: 'Show Contao Version'
    command: "{{ php_path }} {{ websitePath }}/vendor/bin/contao-console contao:version"
    register: version
  - debug:
      var: version.stdout_lines
