---
- hosts: contao
  tasks:

  - name: generate contao-manager/config.json
    template:
      src: contao-manager-config.j2
      dest: "{{ websitePath }}/contao-manager/config.json"

  - name: Generate Contao Manger Password
    shell:  htpasswd -nbB "" {{ contao_manager_pass }} | tr -d ':\n'
    register: contao_manager_pass_crypt
    delegate_to: 127.0.0.1

  - name: Set Contao Manger Password
    set_fact:
      contao_manager_pass_crypt: "{{ contao_manager_pass_crypt.stdout }}"

  - name: generate contao-manager/user.json
    template:
      src: contao-manager-user.j2
      dest: "{{ websitePath }}/contao-manager/users.json"

  - name: create config dir
    file:
      path: "{{ websitePath }}/config"
      state: directory

  - name: generate parameters.yml
    template:
      src: parameters.sh.j2
      dest: "{{ websitePath }}/config/parameters.yml"

  - name: generate config.yml
    template:
      src: config.j2
      dest: "{{ websitePath }}/config/config.yml"

  - name: Generate InstallPassword
    shell:  htpasswd -nbB "" {{ installPassword }} | tr -d ':\n'
    register: psk
    delegate_to: 127.0.0.1

  - name: Set InstallPassword
    set_fact:
      psk: "{{ psk.stdout }}"

  - name: generate localconfig.php
    template:
      src: localconfig.php.j2
      dest: "{{ websitePath }}/system/config/localconfig.php"

  - name: 'Contao Installtool Lock'
    shell: "{{ php_path }} -d memory_limit=-1 {{ websitePath }}/vendor/bin/contao-console contao:install:lock"
    register: instStatus
    failed_when: "instStatus.rc not in [ 0, 1 ]"
  - debug:
     var: instStatus.stdout_lines

  - name: copy default error-page
    copy:
     src: error_layout.html.twig.j2
     dest: "{{ websitePath }}/templates/bundles/ContaoCoreBundle/Error/layout.html.twig"

  - name: 'Clear Cache'
    shell: "{{ php_path }} -d memory_limit=-1 {{ websitePath }}/vendor/bin/contao-console cache:clear"
    register: cacheStatus
  - debug:
     var: cacheStatus.stdout_lines

  - name: 'Clear Warmup'
    shell: "{{ php_path }} -d memory_limit=-1 {{ websitePath }}/vendor/bin/contao-console cache:warmup"
    register: warmupStatus
  - debug:
     var: warmupStatus.stdout_lines

  - name: 'Datenbank aktualisieren'
    command: "{{ php_path }} -d memory_limit=-1 {{ websitePath }}/vendor/bin/contao-console contao:migrate"
    register: dbupdate
  - debug:
     var: dbupdate.stdout_lines
