---
  - name: 'Clear Cache'
    shell: "{{ php_path }} -d memory_limit=-1 {{ websitePath }}/vendor/bin/contao-console cache:clear --env=prod --no-warmup"
    register: cacheStatus
  - debug:
     var: cacheStatus.stdout_lines

  - name: 'Datenbank aktualisieren'
    command: "{{ php_path }} -d memory_limit=-1 {{ websitePath }}/vendor/bin/contao-console contao:migrate"
    register: dbupdate
  - debug:
     var: dbupdate.stdout_lines
