---
  - name: composer.json exists
    stat:
      path: "{{ websitePath }}/composer.json"
    register: composerJsonExists

  - name: create web dir
    file:
      path: "{{ websitePath }}/web"
      state: directory
    when: composerJsonExists.stat.exists == false

  - name: download Contao Manager
    get_url:
      url: https://download.contao.org/contao-manager/stable/contao-manager.phar
      dest: "{{ websitePath }}/web/contao-manager.phar.php"
    when: composerJsonExists.stat.exists == false

  - name: generate composer.json
    template:
      src: composer.j2
      dest: "{{ websitePath }}/composer.json"
    when: composerJsonExists.stat.exists == false
