---
#  Contao Manager
  - name: create contao-manager dir
    file:
      path: "{{ websitePath }}/contao-manager"
      state: directory

  - name: Generate InstallPassword
    shell:  htpasswd -nbB "" {{ installPassword }} | tr -d ':\n'
    register: psk
    delegate_to: 127.0.0.1

  - name: Set InstallPassword
    set_fact:
      psk: "{{ psk.stdout }}"

  - name: Generate Contao Manger Password
    shell:  php -r "echo hash('sha256', '{{ monitoringClientToken | default("monitoringClientToken") }}');"
    register: contao_manager_token
    delegate_to: 127.0.0.1

  - name: Set Contao Manger Password
    set_fact:
      contao_manager_token: "{{ contao_manager_token.stdout }}"

  - name: Generate Contao Manger Secret
    shell:  php -r "echo bin2hex(random_bytes(40));"
    register: contao_manager_secret
    delegate_to: 127.0.0.1

  - name: Set Contao Manger Secret
    set_fact:
      contao_manager_secret: "{{ contao_manager_secret.stdout }}"

  - name: generate contao-manager/config.json
    template:
      src: contao-manager-config.j2
      dest: "{{ websitePath }}/contao-manager/config.json"

  - name: crypt Contao-Manger-User-Password
    shell:  htpasswd -nbB "" {{ contao_manager_pass }} | tr -d ':\n'
    register: contao_manager_pass_crypt
    delegate_to: 127.0.0.1

  - name: Set Contao-Manger-User-Password to variable
    set_fact:
      contao_manager_pass_crypt: "{{ contao_manager_pass_crypt.stdout }}"

  - name: generate contao-manager/user.json
    template:
      src: contao-manager-user.j2
      dest: "{{ websitePath }}/contao-manager/users.json"

  - name: generate contao-manager/config.json
    template:
      src: contao-manager-config.j2
      dest: "{{ websitePath }}/contao-manager/config.json"

# Contao

  - name: create config dir
    file:
      path: "{{ websitePath }}/config"
      state: directory

  - name: generate parameters.yml
    template:
      src: parameters.sh.j2
      dest: "{{ websitePath }}/config/parameters.yml"

  - name: generate config.yml
    template:
      src: config.j2
      dest: "{{ websitePath }}/config/config.yml"

  - name: create system/config dir
    file:
      path: "{{ websitePath }}/system/config"
      state: directory

  - name: generate localconfig.php
    template:
      src: localconfig.php.j2
      dest: "{{ websitePath }}/system/config/localconfig.php"

  - name: 'Contao Installtool Lock'
    shell: "{{ php_path }} -d memory_limit=-1 {{ websitePath }}/vendor/bin/contao-console contao:install:lock"
    register: instStatus
    failed_when: "instStatus.rc not in [ 0, 1 ]"
  - debug:
     var: instStatus.stdout_lines

  - name: create templates/bundles/ContaoCoreBundle/Error dir
    file:
      path: "{{ websitePath }}/templates/bundles/ContaoCoreBundle/Error"
      state: directory

  - name: copy default error-page
    copy:
     src: error_layout.html.twig.j2
     dest: "{{ websitePath }}/templates/bundles/ContaoCoreBundle/Error/layout.html.twig"
